src/ui/ui.c

backport of https://github.com/mate-desktop/marco/pull/153 to 1.8 branch
@flexiondotorg: should fix https://bugs.launchpad.net/bugs/1351942.

[1.8] ui: use correct name for missing icon

---

src/core/window.c

If this field is left uninitialized, a client may mistake Marco to support more than the single update request counter described in EWMH 1.5.

fix uninitialized data field for sending _NET_WM_SYNC_REQUEST event

---

HACKING

run-marco.sh doesn't exist so remove information about it from the
HACKING file

Remove information about non-existent tool run-marco.sh in HACKING

---

src/core/prefs.c

this is achieved by using the same GSettings instance for listening
and reading data. it's an additional fix for the issue with GLib >= 2.43,
https://git.gnome.org/browse/glib/commit/?id=8ff5668a458344da22d30491e3ce726d861b3619

[1.8] prefs: make keybindings change notifications work with GLib >= 2.43

---

src/core/prefs.c

now workspace names actually change on-the-fly when you change them in dconf-editor.
and this works with GLib 2.43 as well.

[1.8] prefs: make workspace name actually change

---

src/core/prefs.c

this is achieved by using the same GSettings instance for listening
and reading data. it's an additional fix for the issue with GLib >= 2.43,
https://git.gnome.org/browse/glib/commit/?id=8ff5668a458344da22d30491e3ce726d861b3619

prefs: make keybindings change notifications work with GLib >= 2.43

---

src/core/prefs.c

now workspace names actually change on-the-fly when you change them in dconf-editor.
and this works with GLib 2.43 as well.

prefs: make workspace name actually change

---

src/ui/tile-preview.c

fix for https://github.com/mate-desktop/marco/issues/158

tile preview: invalidate window before showing

---

src/ui/theme.c
src/ui/theme.h

The theme state used to use GtkStateType, but was ported over to GtkStateFlags,
leaving behind a broken assertion that fails when using certain Metacity
themes, for example Nodoka.
https://bugzilla.gnome.org/show_bug.cgi?id=661286
https://git.gnome.org/browse/mutter/commit/?id=28deea4
https://git.gnome.org/browse/metacity/commit/?id=c9099b4
https://github.com/mate-desktop/marco/issues/205

theme: Remove outdated assertion

---

src/core/window.c

(e.g. delete confirmation dialog, logout dialog...)
it was working that way in gnome 2, I don't know why perberos commented it out...
fixes https://github.com/mate-desktop/caja/issues/443
@NiceandGently @infirit @flexiondotorg
please test it for any possible regressions :smile:

window menu: make minimize item insensitive when window should not be minimized

---

src/50-marco-global-key.xml.in
src/core/keybindings.c
src/core/screen-private.h
src/core/workspace.c
src/core/workspace.h
src/include/all-keybindings.h
src/org.mate.marco.gschema.xml

This is fixed version of previously rewerted pull request. It is partly cleaned and the affected atl+tab problem is fixed by placing keybind definition in all-keybindings.h on the end of file. This is not perfect, but I did not found any better solution.

Possible keybinding to switch to previous workspace.

---

src/org.mate.marco.gschema.xml

This is changed to match the description of the setting. In addition, the behavior to open new windows on the top left of the screen has been consistent for over a decade. I believe it's counter-productive to change this now.

Reverting center-new-windows default to false. 

---

src/ui/theme.c

gtk3 can use style context before widget realization

gtk3: fix assertion 'gtk_widget_get_realized (widget)' failed

---

src/core/effects.c

fixes https://github.com/mate-desktop/marco/issues/200
ported to Marco from https://github.com/GNOME/metacity/commit/f25b7760b7430b674afdb4de1e2072cd99ea3fbc

effects: remove hack that made Marco crash in certain situations

---

src/Makefile.am

Differences between Gtk2 and Gtk3 builds of libmarco-private are even bigger than linked GTK+ version, libmarco-private's API itself is different.

Bump libmarco-private's sover in Gtk3 build

---

src/ui/tile-preview.c
src/ui/ui.c

this avoids warnings like this:
Warning of Windowmanagement:Log level 16: State 4 for context 0x55988f9ad950
doesn't match state 128 set via gtk_style_context_set_state ()

GTK+3: Get values from GtkStyleContext states properly

---

src/ui/ui.c

The pull request forces a specific window scale for `marco`, instead of using the default or user configured scale. 
Tested on a Dell XPS 15 with 3840 x 2160 and `GDK_SCALE=2` and `GDK_DPI_SCALE=0.5` exported to the Xsession. Windows and screen dimensions are now correct.

Forces a window scale of 1 for Marco. Closes #335

---

src/core/display.c
src/core/keybindings.c

When a client is passively grabbing keys or mouse clicks that it does not need, it sends them up for other clients to process (this sets the `send_event` flag inside `XEvent`).
Often in this situation, the event contains the wrong window (either root, for global keybindings, or the original client itself). This means that Marco will attempt to process the event for the wrong window.
This is not an issue for global bindings within Marco, as the focused/current window does not matter. However, for shortcuts that operate directly on specific windows, the events gets lost.
This change addresses this issue by determining which is the currently-focused (for key grabs), or under-the-pointer (for button grabs), window, regardless of which client forwarded the event.

Fix synthetic keybinding/button-grab window

---

src/core/display.c

use GdkSeat for >= gtk+-3.20
Please test.

display: don't use deprecated GDK_DEVICE_MANAGER

---

src/core/constraints.c
src/core/keybindings.c
src/core/window-private.h
src/core/window.c

Determine whether the user is initiating a resize action on a tiled
window. If the user is trying to grab the window for resizing
horizontally from the edge that's farther away from the screen edge,
allow the resize to occur. Otherwise maintain the current tile geometry.
Also modified the window hints to allow resizing from the window menu.
Fixes #250

Allow tiled windows to be resized horizontally

---

src/core/keybindings.c

We have this build warning since the PR https://github.com/mate-desktop/marco/pull/308 merged with the commit https://github.com/mate-desktop/marco/commit/5ded52f5e98d60abb903cc9194714a9b293ad482

keybindings.c: Fix build warning: assignment discards ‘const’ qualifier from pointer target type

---

src/50-marco-window-key.xml.in
src/core/constraints.c
src/core/keybindings.c
src/core/window-private.h
src/core/window.c
src/include/all-keybindings.h
src/org.mate.marco.gschema.xml

Hi,
I implemented proper keybinds for moving windows between monitors that work with tiled/maximized/fullscreen windows.
Please test it and sorry for the PR spam :)
Closes #320

Multimonitor keybinds

---

src/core/keybindings.c

When two or more monitors are connected, the move_to_center keybind moves the window to the center of the whole xinerama, which in case of two monitors means that the window lands between the monitors. I think that this is unwanted behavior (?). This is a small fix that moves the window to the center of the monitor that the window belongs to.

Fixes move_to_center moving window between monitors

---

src/core/atomnames.h
src/core/window.c

Fixes https://github.com/mate-desktop/marco/issues/383 if :backdrop state supported in themes
ported from:
https://github.com/GNOME/metacity/commit/4ccb99a50c54f345c4c7d9ac77f1ea76bc6c7c74

window: add _NET_WM_STATE_FOCUSED hint to _NET_WM_STATE

---

src/ui/frames.c

This seems to fix the resize cursor being stuck in the wrong image. I went through my checklist from when I added the scaling to marco and couldn't find any regressions, but please test to make sure it works for you.

Fix frame geometry to avoid stuck resize cursor

---

src/core/keybindings.c
src/core/screen.c
src/ui/tabpopup.c

These are some improvements to the workspace and alt+tab switchers:
* If there's only one workspace, don't show the pop-up if the user presses the shortcut (Ctrl+Alt+arrows)
* When switching apps with Alt+Tab, the shadow now shows up immediately, rather than on the second Tab press. It also adds a border around it so that it doesn't look cut-off, and prevents the outline from being created if we don't need it

tab popup improvements

---

src/core/display.c
src/core/errors.c
src/core/iconcache.c
src/core/keybindings.c
src/core/screen.c
src/core/stack.c
src/core/window.c
src/core/xprops.c
src/include/errors.h

avoid deprecated:
gdk_error_trap_push
gdk_error_trap_pop_ignored
gdk_error_trap_pop

errors.c: avoid deprecated 'gdk_error_trap...' functions:

---

configure.ac

Keep silent output of make, except errors and warnings.

enable silent output when building

---

src/core/screen.c

Fixes https://github.com/mate-desktop/marco/issues/445
not sure how to reproduce the issue step by step, but this commit is needed
@raveit65 @lukefromdc please test, it fixes the issue?

screen: avoid 'NULL' in 'meta_error_trap...' functions

---

src/core/screen-private.h
src/core/screen.c
src/core/window.c
src/include/common.h
src/ui/tabpopup.c
src/ui/theme.c
src/ui/ui.c

Alt+Tab and Workspace popups should be sized relative to the screen size.
This way they look nice and large regardless of the display resolution.
Also, given much larger modern resolutions, icon sizes should be larger by default.
Fixes #333 
Fixes #363

Increase icon size on tab and workspace popups

---

.travis.yml

The docker-build on the master branch is stable, now switch to it.

Now to use docker-build on the master branch

---

src/compositor/compositor-xrender.c

Fixes Clang static analyzer warning:
```
compositor/compositor-xrender.c:587:10: warning: Potential leak of memory pointed to by 'data'
return ximage;
^~~~~~
```

compositor-xrender: Fix memory leak

---

src/core/testasyncgetprop.c
src/core/xprops.c

Fixes Clang static analyzer warnings:
warning: Call to function 'strcpy' is insecure as it does not provide bounding of the memory buffer. Replace unbounded copy functions with analogous functions that support length arguments such as 'strlcpy'. CWE-119

[Security] Use 'g_strlcpy' instead of 'strcpy'

---

src/core/screen.c

Fixes Clang static analyzer warning:
```
core/screen.c:754:16: warning: Use of memory after it is freed
result = g_list_prepend (result, info);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

screen: Fix use of memory after it is freed

---

src/core/constraints.c

I don't understand why we should judge whether the window is decorated or not.I think it would be better to remove this judgment so that problems with header-bar windows can be avoided.

MATE uses header bars windows problematic

---

src/core/boxes.c

avoid Clang static analyzer warning:
```
core/boxes.c:412:15: warning: Use of memory after it is freed
if (meta_rectangle_contains_rect (a, b))
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
I am not sure if this is the correct way, but fixes the warning

boxes: avoid false positive warning in Clang static analyzer

---

.travis.yml

The Travis document https://docs.travis-ci.com/user/deployment/#pull-requests said that:
>Pull Requests #
>Note that pull request builds skip the deployment step altogether.
Only commit can trigger the deploy, so create new branch for test.
@raveit65 
Can you set marco to use `gh-pages` branch as the page source?
That branch is ready: https://github.com/mate-desktop/marco/tree/gh-pages

Enable Clang Static Analyzer for marco

---

src/core/window.c

avoid Clang static analyzer warning:
```
core/window.c:3580:34: warning: The right operand of '+' is a garbage value
new_w = window->rect.width + fgeom.left_width + fgeom.right_width;
^ ~~~~~~~~~~~~~~~~
```

window: avoid clang warning: garbage value

---

src/core/window.c

Fix for https://bugzilla.redhat.com/show_bug.cgi?id=1701799
MATE Menu Bar often has unreadable text with none MATE themes, which support backdrop state.
Set the NET_WM_STATE_FOCUSED property on windows of type dock or
spashscreen so that they don't get the state GTK_STATE_FLAG_BACKDROP
set by default.
Based on:
https://gitlab.gnome.org/GNOME/metacity/commit/b3ef887
origin xfwm4 commit:
https://git.xfce.org/xfce/xfwm4/commit/?id=0feb29e78bb3
For testing use adwaita theme which has backdrop state support.

window: make docks and spashscreens appear focused

---

src/ui/theme-viewer.c

origin commit by:
https://gitlab.gnome.org/GNOME/metacity/commit/542a2b4
Please test.

theme-viewer: avoid deprecated gtk_widget_override_background_color

---

src/core/frame.c
src/include/ui.h
src/ui/frames.c
src/ui/frames.h
src/ui/ui.c

From origin commit:
This way the xserver never paints the frame background, even if
the client window is destroyed. This allows us to have clean
destroy window animation.
There is no problem with interactive resizing because applications
are using the XSync protocol, so we're not painting unless the
client has redrawn.
https://bugzilla.gnome.org/show_bug.cgi?id=734054
origin commit:
https://gitlab.gnome.org/GNOME/metacity/commit/78c283c
Beside from that PR removes a deprecation: gtk_style_context_set_background

ui: always set the frame background to None

---

src/marco.desktop.in

mate-session[1210]: WARNING: Could not parse desktop file /usr/share/applications/marco.desktop: El fitxer de claus no conté una clau «Name» en el grup «Desktop Entry»
mate-session[1210]: GLib-GObject-CRITICAL: object GsmAutostartApp 0x7f158800ede0 finalized while still in-construction
mate-session[1210]: GLib-GObject-CRITICAL: Custom constructor for class GsmAutostartApp returned NULL (which is invalid). Please use GInitable instead.
mate-session[1210]: WARNING: could not read /usr/share/applications/marco.desktop

Fix Could not parse desktop file marco.desktop

---

src/tools/marco-window-demo.c

The window type of splash is `_NET_WM_WINDOW_TYPE_SPLASH` not `_NET_WM_WINDOW_TYPE_SPLASHSCREEN`.

fix window type for splash

---

src/core/keybindings.c
src/core/keybindings.h
src/include/tabpopup.h
src/ui/tabpopup.c

Now also the up/down arrow keys can be used in the alt+tab popup, not only left/right arrow keys. 
See also #330

Allow use of up/down arrow keys in alt+tab popup

---

src/core/display-private.h
src/core/display.c
src/include/tabpopup.h
src/ui/tabpopup.c

Now it's possible to move the focus rectangle in the alt+tab popup by mouse clicks.
Fixes #364.

Handle mouse clicks in Alt+Tab Popup

---

configure.ac
src/Makefile.am

See docs https://www.sourceware.org/autobook/autobook/autobook_61.html#Library-Versioning
This is needed because current libmarco-private is incompatible to previous version.

 bump LT_VERSION_INFO (soname version)

---

.travis.yml

Fix `make dist` include .gmo files.
The result of `$ tar tf marco-*.tar.xz|grep po`:
https://travis-ci.org/mate-desktop/marco/jobs/549023754#L2256

fix make dist to remove .gmo files

---

src/core/window.c

When changing window state, we want to change the allowed action hints
so that other applications, mainly the taskbar, can disable menu entries
that do not make much visual sense. For example, unmaximizing
a minimized window: even though this operation is possible, it causes
user confusion as there is no visibility until the user unminimizes it.
Fixes https://github.com/mate-desktop/mate-panel/issues/860

window: Update allowed action hints

---

src/core/window.c
src/ui/frames.c
src/ui/frames.h
src/ui/ui.c

This should completely fix #105, so that apps which prefer dark theme will also have dark window decoration if the theme supports that. If the theme doesn't support that, everything should work as before.
How to test:
1. Use some theme which has light and dark variants. Light variant should support dark theming for apps that prefer the dark theme (they set `gtk-application-prefer-dark-theme` in `GtkSettings`). I've used Arc theme.
2. Run some app which has the setting to prefer the dark theme. I've used gnome-terminal. Set the dark theme preference in `Edit > Preferences > General > Theme variant: Dark`.
Without this PR:
With this PR:

fix dark window decorations on apps which prefer dark theme

---

src/core/async-getprop.c
src/core/xprops.c

Fixes Clang static analyzer warnings:
```
core/xprops.c:761:9: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
raw = (xPropWMHints*) results->prop;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/xprops.c:883:9: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
raw = (xPropSizeHints*) results->prop;
core/async-getprop.c:277:11: warning: Casting a non-structure type to a structure type and accessing a field can lead to memory access errors or data corruption
reply = (xGetPropertyReply *)
^~~~~~~~~~~~~~~~~~~~~
```

Fix cast from non-struct type to struct type

---

po/Makevars

https://travis-ci.org/mate-desktop/marco/jobs/578291133#L1085
```
xgettext: warning: file 'src/org.mate.marco.gschema.xml' extension 'xml' is unknown; will try C
```

Fix build warning about xgettext

---

src/core/display.c

I'm not 100% sure, but I feel like `break` is missing here

 display.c: add missing "break"

---

src/core/window.c

window.c: remove unused variable

---

src/core/frame.c

Use the window's visual in all cases, fix problems with drivers forcing use of blit rather than pageflip mode when comppositing is not used or window is unredirected
Fix https://github.com/mate-desktop/marco/issues/540
Apply https://gitlab.gnome.org/GNOME/metacity/commit/5863176a2bd659c8d9a3d1c7b023a27c1a8c0aa5

Fix use of RBGA visual in frame.c when compositing is not in use

---

.travis.yml
configure.ac
meson.build

- Remove -ansi from CFLAGS.
- By default, CFLAGS:
-Wall -Wchar-subscripts -Wmissing-declarations
-Wnested-externs -Wpointer-arith -Wcast-align
-Wsign-compare
- If --enable-more-warnings, add -Wextra to CFLAGS.
- Requires autoconf-archive package.

build: add --enable-more-warnings configure flag

---

src/ui/tabpopup.c

```
ui/tabpopup.c:176:7: warning: format not a string literal, argument types not checked [-Wformat-nonliteral]
176 |       tmp = g_markup_printf_escaped (formatter, str);
|       ^~~
```

Remove warning: format not a string literal, argument types not checked

---

src/core/testboxes.c

core/testboxes.c:34:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
core/testboxes.c:103:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
core/testboxes.c:120:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
core/testboxes.c:148:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
core/testboxes.c:167:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
core/testboxes.c:190:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
core/testboxes.c:589:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
core/testboxes.c:681:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
core/testboxes.c:725:1: warning: function …

remove warnings: function declaration isn’t a prototype

---

src/core/testboxes.c

Eeeks, testing floating points for equality ...
upstream commit:
https://gitlab.gnome.org/GNOME/mutter/commit/0fccb0fc8
Closes #473

testboxes: Fix find_closest_point_to_line() test

---

.travis.yml
configure.ac
src/Makefile.am
src/tools/Makefile.am
src/wm-tester/Makefile.am

It removes --enable-more-warnings, since it is recommended to use
--enable-compile-warnings=maximum

Use WARN_CFLAGS which are only set with --enable-compiler-warnings

---

configure.ac

--enable-debug=yes/info/profile/no
By default, compiler debug flags are disabled.
Test 1:
```
$ ./autogen.sh && grep "^CFLAGS" config.log
CFLAGS=' -Wall -Wcast-align -Wchar-subscripts -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wsign-compare -Wshadow'
```
Test 2:
```
$ ./autogen.sh --enable-debug && grep "^CFLAGS" config.log
CFLAGS=' -g -O0 -Wall -Wcast-align -Wchar-subscripts -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wsign-compare -Wshadow'
```
It requires https://github.com/mate-desktop/mate-common/pull/29

Set compiler debug flags using MATE_DEBUG_CHECK

---

src/ui/theme.c
src/ui/theme.h

When loading window control buttons and icon as pixbufs, we just set
them as the source for the cairo context used to paint them. Instead, we
now convert them to cairo surfaces and scale them to the correct display
density before painting them.
This allows us to load higher resolution assets (i.e. at twice the size)
and by explicitly setting the intended size in the theme draw_ops, we
can then scale them down to fit lower resolution displays, or render
them at full density for HiDPI displays.

theme: Render window control buttons and icons as surfaces

---

src/Makefile.am

DATADIRNAME was established by [glib-gettext.m4](https://github.com/GNOME/glib/blob/master/m4macros/glib-gettext.m4) before the migration to gettext in https://github.com/mate-desktop/marco/commit/3324c2850b96cb99efb0c90cbf37e563a17f6f7b.
Use $([datadir](https://www.gnu.org/software/automake/manual/html_node/Standard-Directory-Variables.html))/locale instead of $(prefix)/@DATADIRNAME@/locale from now on.
Catalan screenshots:

Fix MARCO_LOCALEDIR displaying the translated messages

---

src/core/prefs.c
src/core/screen.c
src/core/window.c
src/include/common.h
src/include/tabpopup.h
src/org.mate.marco.gschema.xml
src/ui/draw-workspace.c
src/ui/tabpopup.c

This changes how the Alt+Tab and Workspace Switcher popups are drawn. The are now styled as OSD windows with a bunch of stylistic improvements. Also more things are drawn as cairo surfaces and some gschema values have been changed to make them compatible with the new design.

tabpopup: Draw popups as OSD windows

---

src/core/keybindings.c
src/core/prefs.c
src/core/window-private.h
src/core/window.c
src/include/prefs.h
src/org.mate.marco.gschema.xml

Adding a new option to allow tile size cycling. When enabled, using the
keyboard shortcut for tiling multiple times in a row cycles the window
through different sizes (1/2 -> 1/3 -> 1/4 -> 3/4 -> 2/3 -> Untiled).

window: Add optional tile size cycling

---

src/ui/theme.c

By scaling the pixbuf when loading, existing assets can be used.
meta_theme_load_image() is only run once for each image when the theme loads, so the cost of loading them twice is relatively minor.
Examples (in hidpi):
(this is with or without https://github.com/mate-desktop/mate-themes/commit/8f56d6be5a2e3116699703da9f103a964ee7222d)

theme.c: Fix window control hidpi rendering for all themes.

---

src/compositor/compositor-private.h
src/compositor/compositor-xrender.c
src/compositor/compositor.c

This reverts commit df56628979abc17474b001c58c28c6f3637ada9d.
It causes an issue where windows remain in the background even when
being drawn in the foreground.

Revert "compositor: fix possible crash closing/destroying window"

---

src/core/xprops.c

Backports a fix for a memory leak fixed on Metacity but not on Marco.
This brings down normal usage on my machine from 256 Mb to 180 something
Origin commit :
https://gitlab.gnome.org/GNOME/metacity/commit/c87f73f3b4413720a2f3e6a672826d3fec7f77a9
"
XmbTextPropertyToTextList documentation says that XFreeStringList
should be used to free the storage for the list and its contents.
"

Xprops fix memory leak.

---

src/core/constraints.c
src/core/window.c

This PR backports the commit https://gitlab.gnome.org/GNOME/metacity/commit/1fafd279006ece8cf664fd777143cdfafbefad6d on Metacity to Marco.
It should fix issue #316 .
I don't have multi monitors so i cannot test.
It supersedes the troubled PR i did :-1: 
Bug 781946 - Non-native decorated windows stuck maximised on secondary screen with Marco/Metacity

Dual monitor windows stuck fullscreen fix

---

src/core/util.c
src/include/util.h

It removes the warnings below:
```
core/core.c:505:3: warning: dereference of NULL ‘window’ [CWE-690] [-Wanalyzer-null-dereference]
505 |   meta_window_change_workspace (window,
|   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
506 |                                 meta_screen_get_workspace_by_index (window->screen,
|                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
507 |                                                                     new_workspace));
|                                                                     ~~~~~~~~~~~~~~~
‘meta_core_change_workspace’: events 1-2
|
|  499 | meta_core_change_workspace (Display *xdisplay,
|      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
|      | |
|      | (1) entry to ‘meta_core_change_workspace’
|......
|  503 |   MetaWindow …
```

util: meta_bug raises SIGABRT so it shouldn't return

---

meson.build
meson_options.txt

Drop the enable from `--enable-foo` boolean options; Meson has boolean values, so `-Denable-foo=true` would read as redundant, and `-Denable-foo=false` would read as contradictory. Use `-Dfoo=true` or `-Dfoo=false` instead
https://wiki.gnome.org/Initiatives/GnomeGoals/MesonPorting

meson: improve

---

src/compositor/compositor-xrender.c
src/core/frame.c

This latest change works fine, but floods my logs with
```
Window manager warning: Log level 16: Visible region is null
```
Also reformatted recent code change to fix styling issues.

Remove unnecessary warnings about visible region

---

configure.ac
src/core/constraints.c

If the decimal value is from .1 to .5, round(arg) returns
the integer value less than the argument. Otherwise, if
the decimal value is from .6 to .9, it returns the
integer value greater than the arg.

Use rounded values instead of truncate them

---

src/tools/marco-window-demo.c
src/ui/draw-workspace.c
src/ui/theme-parser.c
src/ui/theme-viewer.c

```
marco-window-demo.c:1054:32: warning: implicit conversion from ‘enum <anonymous>’ to ‘GtkWrapMode’ [-Wenum-conversion]
1054 |                                PANGO_WRAP_WORD);
|                                ^~~~~~~~~~~~~~~
--
ui/draw-workspace.c:109:44: warning: implicit conversion from ‘GtkStateType’ to ‘GtkStateFlags’ [-Wenum-conversion]
109 |     meta_gtk_style_get_light_color (style, state, &color);
|                                            ^~~~~
ui/draw-workspace.c:111:34: warning: implicit conversion from ‘GtkStateType’ to ‘GtkStateFlags’ [-Wenum-conversion]
111 |     get_background_color (style, state, &color);
|                                  ^~~~~
ui/draw-workspace.c:160:39: warning: implicit conversion from ‘GtkStateType’ to ‘GtkStateFlags’ [-Wenum-conversion]
160 | …
```

Remove enum conversion warnings

---

src/include/common.h

test: Remove cache
```
$ rm -fr .cache
```
closes #631

common: window icon (META_DEFAULT_ICON_NAME) is no longer available

---

src/ui/theme.c

```
ui/theme.c:78: warning: macro "ALPHA_TO_UCHAR" is not used [-Wunused-macros]
78 | #define ALPHA_TO_UCHAR(d) ((unsigned char) ((d) * 255))
| 
```

theme: macro "ALPHA_TO_UCHAR" is not used

---

src/ui/frames.c

Based on Metacity commit https://gitlab.gnome.org/GNOME/metacity/-/commit/0b2f5ad0a2f30726ac0dc59aa59f7f513e91c832
Fixes transparent windows on issue #486

Do not call cairo paint on generate_pixmaps.

---

configure.ac

The default value for meson build is false.
https://github.com/mate-desktop/marco/blob/05ffd59e8b5a0c125e21f487e91fb0d456b63fa3/meson_options.txt#L1-L2

build: by default disable also the verbose mode for autoconf

---

src/ui/frames.c

Reported by Eclipse IDE's Code Analysis

frames: Unused static functions 'get_client_region', 'get_frame_region'

---

src/core/bell.c

Reported by Eclipse IDE's Code Analysis

bell: Unused static function 'bell_flash_screen'

---

src/core/testasyncgetprop.c

Reported by Apache NetBeans IDE

testasyncgetprop: Mismatching the argument type 'unsigned long' and conversion specifier 'ld'

---

src/core/display.c
src/ui/menu.c
src/wm-tester/test-gravity.c

```
test-gravity.c:69:32: warning: declaration of ‘doubled’ shadows a global declaration [-Wshadow]
ui/menu.c:411:33: warning: declaration of ‘md’ shadows a previous local [-Wshadow]
ui/menu.c:412:36: warning: declaration of ‘key’ shadows a previous local [-Wshadow]
ui/menu.c:413:43: warning: declaration of ‘mods’ shadows a previous local [-Wshadow]
core/display.c:406:9: warning: declaration of ‘i’ shadows a previous local [-Wshadow]
core/display.c:5243:20: warning: declaration of ‘display’ shadows a previous local [-Wshadow]
core/display.c:5293:20: warning: declaration of ‘display’ shadows a previous local [-Wshadow]
```

warning: declaration of a variable shadows a previous local

---

src/core/window-props.c

```
core/window-props.c:1608:3: warning: ‘g_memdup’ is deprecated: Use 'g_memdup2' instead [-Wdeprecated-declarations]
1608 |   MetaWindowPropHooks *table = g_memdup (hooks, sizeof (hooks)),
|   ^~~~~~~~~~~~~~~~~~~
```

window-props: g_memdup is dreprecated from glib 2.68

---

src/core/window.c

When tiling a maximized window, we should keep track of the saved
rectangle so that tiling does not reset our window size. Otherwise,
untiling the previously maximized window will end up with an unmaximized
full-size window, rather than the original window size.
To reproduce:
1. Open a window (pluma, mate-termina, etc)
2. Maximize
3. Tile right using keyboard shortcuts
4. Restore window
a. Before this patch, the restored window size is a full size window
b. After this patch, the restored window size is the original size before maximizing

window: Track window rectangle before tiling

---

src/core/window.c

When corner-tiling a maximized window, we should keep track of the saved
rectangle so that tiling does not reset our window size. Otherwise,
untiling the previously maximized window will end up with an unmaximized
full-size window, rather than the original window size.

window: Track window rectangle before corner tiling

---

src/core/iconcache.c
src/core/iconcache.h
src/core/window.c
src/include/ui.h
src/ui/ui.c

Some files do not report their application icons correctly in the window
properties. This patch allows the marco UI to search for the
corresponding .desktop file and render the icon in the desktop info on
both the alt-tab popup and the window mini-icon.
Before:
After:

iconcache: Use GDesktopAppInfo to find correct application icons

---

src/compositor/compositor-xrender.c
src/core/window.c
src/include/window.h

This pull request prevents shadows being rendered for left and right side titled windows. This behaviour is consistent with maximised windows, which also do not render shadows.
The rationale for this change is so that when two windows are titled along side each other, it prevents central shadows bleeding into the touching points of the windows.
metacity-theme-x.xml has provision to style left/right titled windows. This patch makes it possible to create window themes that present clean side-by-side tiled windows, as shown below:

window: Do not render shadows on left/right tiled windows

---

src/ui/draw-workspace.c

Commit 6b05da5e49996a2101edfd703dd3f5d91011d726 introduced a Cairo surface leak, by calling `gdk_cairo_surface_create_from_pixbuf()` but then never freeing those surfaces with `cairo_surface_destroy()`.
This manifested in leaking resources when switching between virtual desktops, as observed using xrestop (`Pxms` column), which made the desktop slow and ultimately unusable after a few weeks of uptime.
Fixes #685

tabpopup: fix cairo surface leak

---

HACKING
README
README.md

Update README README.md HACKING with gtk+ >= 3.22 and suggest github instead of bugzilla for patches.

README: Update gtk requirement and patch submission

---

src/core/main.c

test:
```
$ marco -v
marco 1.26.0
```

main: Add short name for version option

---

src/core/prefs.c

```
Direct leak of 424 byte(s) in 1 object(s) allocated from:
#0 0x7fd3bc5ee93f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7fd3bb342b7f in g_malloc ../glib/gmem.c:106
#2 0x7fd3bb342ec2 in g_malloc_n ../glib/gmem.c:344
#3 0x7fd3bb642c1b in g_settings_schema_list_keys ../gio/gsettingsschema.c:1112
#4 0x7fd3bc40e5e7 in init_bindings core/prefs.c:1753
#5 0x7fd3bc40e73b in init_window_bindings core/prefs.c:1774
#6 0x7fd3bc40ba95 in meta_prefs_init core/prefs.c:978
#7 0x4040fb in main core/main.c:467
#8 0x7fd3bae40b74 in __libc_start_main (/lib64/libc.so.6+0x27b74)
Direct leak of 523 byte(s) in 51 object(s) allocated from:
#0 0x7f208ab9893f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f20898ecb7f in g_malloc ../glib/gmem.c:106
#2 0x7f20898ecec2 in g_malloc_n …
```

prefs: fix memory leak

---

src/meson.build

```
src/meson.build:214:7: ERROR: Function does not take positional arguments.
```

build: fix meson build

---

src/core/constraints.c
src/core/display-private.h
src/core/display.c
src/core/edge-resistance.c
src/core/window-props.c
src/core/window.c
src/ui/theme-parser.c

```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
core/constraints.c:631:5: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
meta_rectangle_contained_in_region (info->usable_screen_region,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/constraints.c:644:5: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
meta_rectangle_contained_in_region (info->usable_xinerama_region,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
core/constraints.c:663:9: warning: implicit conversion changes …
```

Fix implicit conversion changes signedness: 'gboolean' to 'guint'

---

src/core/boxes.c

```
core/boxes.c:1372:15: warning: implicit conversion turns string literal into bool: 'char [53]' to '_Bool' [-Wstring-conversion]
g_assert ("Some idiot wanted to sort sides of different types.\n");
~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gtestutils.h:232:59: note: expanded from macro 'g_assert'
if G_LIKELY (expr) ; else \
~~           ^~~~
/usr/include/glib-2.0/glib/gmacros.h:1091:25: note: expanded from macro 'G_LIKELY'
#define G_LIKELY(expr) (expr)
^~~~
```

boxes: fix build warning -Wstring-conversion

---

src/core/window.c

fixing dialog windows in wine.
see https://github.com/mate-desktop/marco/issues/735

window: do not disable fullscreen for dialogs

---

src/core/display.c

This reverts https://github.com/mate-desktop/marco/commit/f96255beb (except for some unnecessary whitespace changes) to fix https://github.com/mate-desktop/marco/issues/647
I've been using this for a few days and had no issues at all. It works fine with multiple workspaces too.

Fix window focus stack

---

src/core/window-props.c

Basically, it adds a check to see if the title is empty, not just null.

Show correct window title when owned by superuser. Issue #749

---

configure.ac
meson_options.txt

Verbose mode is not enabled when running Macro by default, but can be toggled dynamically as needed, e.g. for debugging a user issue, possibly even while it happens.
For some reason Meson was introduced with this option off by default (d86c29b0e518f765e7570573c76bc033fbd17f6d), and we later forwarded to Autoconf with no other rationale than getting in line with Meson (397e31879bf79861a1a21ec4e2a75017e243d34b).
I was surprised to see this disabled by default, and so was @muktupavels, see short discussion on https://github.com/mate-desktop/marco/pull/748#issuecomment-1404918784.
If this is deliberate, you can close this, and possibly explain why it is better to have this disabled by default?

Build with verbose mode support by default

---

src/core/window-props.c

Fix losing title of windows with a 3 or 4 bytes first character

---

src/core/frame.c
src/core/screen.c
src/include/tabpopup.h
src/include/ui.h
src/ui/frames.c
src/ui/frames.h
src/ui/tabpopup.c
src/ui/ui.c

Thus far, the UI code enabled internal compositing code if compositing has been requested (i.e., the `compositing-manager` preference is turned on).
Unfortunately, requesting compositing doesn't mean that it needs to be available. Meta core code handles this gracefully by checking if X server extensions related to compositing are available and only enabling the internal compositor if everything looks alright, but this is not exposed to UI code directly.
If UI code enables compositing parts merely based upon the preference and doesn't check if compositing is actually available, we end up with black borders around windows and other weird effects.
This can be reproduced via X2Go/NX or testing with nested X servers such as Xephyr and disabling the XComposite extension.
This PR introduces …

Only enable compositing in UI code if it's actually available.

---

src/core/workspace.c

When the active workspace is changed, marco figures out which window should get focus by calling `focus_ancestor_or_top_window`. In some cases that call might include a window that should not get focus as `not_this_one`.
When `not_this_one` refers to a window, the function will check to see if it has a parent, and if it does, it will ignore the new workspace's `mru_list` and will focus that parent window. However, it doesn't check to see if the parent window is actually on the new workspace. If the parent isn't on the new workspace, focusing it will drag it over, including the transient window that was supposed to be ignored. This isn't the result a user would likely expect, and is made more confusing by the parent window being minimized, stuck that way until the user switches to another …

workspace: ignore not_this_one if not in current workspace

---

src/themes/eOS/meson.build

Follow-up of 4a2a5dc092814bfe ("eOS theme: Add single button backgrounds")
Without this fix these PNGs are installed when using autotools but not using meson.

themes/eOS/meson.build: Install missing PNGs

---

src/core/window-props.c

Fixes #301.
---
Disclaimer: I didn't test this, I don't actually use flatpacks or such.  However, given a check was clearly the wrong way around, and I imported another fix from Metacity, it might just work.
If this doesn't do it, possibly importing Metacity commits dade470e13292c58822b0c180019caf0ea3862f3 c6584a38a234726c1128d044fd7cc5a0f8379c69 c5136ec907fab167ffddfe4d10c3902c6c5d8852 8430e8436cb6bac732c00de5b5a3c3d73be62871 a7d6f11b3e712751b010a8f7622b148c93765f70 7c1cc3ca1d8131499b9cf2ef50b295602ffd6112 3e6358113acf61e0c68419bec6cc68a29603a2ec might help (it's mostly refactoring in the end tho, so I'm hopeful the simpler patch here would work).
CC @lukefromdc @lambdanil @tidux @rusty-snake @caiodev (and everybody else from #301), please test if you can :)

Fix client pid check

---

src/ui/theme.c

Apply Fitt's law to corner window buttons by extending the clickable area all the way to the edge of the screen on maximized/tiled windows. This means that a user moving the pointer all the way to the top-right corner and clicking, will close the maximized (or right-tiled) window. The same applies for top-left on maximized and left-tiled windows.
Fixes https://github.com/mate-desktop/mate-themes/issues/315

theme: Extend button clickable area to edge of screen

---

.github/workflows/builds.yml
.github/workflows/release.yml

Whenever there's a new v* tag, GitHub will use distcheck to generate tarballs, create a proper release, and trigger the mate-desktop.org webhook.

ci: Trigger full release on new tag
