mate-desktop/marco

src/ui/tile-preview.c
draw non transparent tile border.
With border preview window looks more completely.
=> gtk3: draw tile border

src/tools/marco-window-demo.c
initialized contents for gtk2/3
=> gtk3: unintialized variable

src/org.mate.marco.gschema.xml
Reverts https://github.com/mate-desktop/marco/pull/203.
=> Make center-new-windows true after all, and change the description to better match it

src/compositor/compositor-private.h, src/compositor/compositor-xrender.c, src/compositor/compositor.c, src/core/screen.c, src/include/compositor.h, src/include/ui.h, src/ui/ui.c
fixes https://github.com/mate-desktop/marco/issues/232
@raveit65 @lukefromdc
please test this big change :smile:
=> [GTK+3] re-add ability to show alt-tab thumbnails when compositor is on

src/core/delete.c, src/core/keybindings.c, src/core/main.c, src/core/window-props.c, src/ui/tile-preview.c, src/ui/ui.c
=> deprecations

src/compositor/compositor-xrender.c
Based on metacity commit: a0b8c85c4c0cfb9a378d7c5554af15fdd7703155
From: Alberts Muktupāvels <alberts.muktupavels@gmail.com>
=> compositor: don't try to paint window that is not viewable, fix #324

.travis.yml
Maybe this docker image is ok.
=> change to use archlinux/base image

.travis.yml
=> add travis-ci config

README, README.md
Show the build status icon at README, like this: https://github.com/mate-desktop/marco/tree/build-status-icon#marco-
=> Show build status icon

src/ui/frames.c
please, don't push to the 1.22 release
EDIT: latest changes:
based in the mutter commits:
https://gitlab.gnome.org/GNOME/mutter/commit/b8b0dc5c78008647f5833f63d88456025f17bd08
https://gitlab.gnome.org/GNOME/mutter/commit/669c9da2a48d9a5573edee09065b8558c1d07035
=> frames: avoid deprecated 'gtk_widget_set_double_buffered'

src/core/delete.c
=> delete: remove old code

src/core/boxes.c, src/core/testboxes.c, src/core/workspace.c, src/include/boxes.h
=> Replace meta_rectangle_free_list_and_elements with g_list_free_full

src/core/util.c, src/core/window.c, src/include/util.h
=> Replace meta_free_gslist_and_elements with g_slist_free_full

src/ui/menu.c
Fixes double free of menu_data introduced in b0df98a
=> Remove unnecessary GClosureNotify methods

src/core/core.c, src/core/iconcache.c, src/core/iconcache.h, src/core/main.c, src/core/prefs.c, src/core/screen.c, src/core/window.c, src/include/common.h, src/include/core.h, src/include/prefs.h, src/org.mate.marco.gschema.xml, src/ui/preview-widget.c, src/ui/ui.c
=> make icon size configurable

src/ui/gradient.c, src/ui/gradient.h, src/ui/theme.c, src/ui/theme.h
=> Fix gradients

src/core/keybindings.c
Fixes #414
Fixes #394 
Please test it and let me know. :)
=> Fixed moving windows to edges to work with CSD clients.

src/ui/frames.c, src/ui/theme.c
Based on
https://gitlab.gnome.org/GNOME/metacity/commit/5aecb8336c6c90a9ad1bb46295ca60624f5a44aa
https://gitlab.gnome.org/GNOME/metacity/commit/1dcde194923c2f6791de0c6b5d6bd6c3b66b80da
https://gitlab.gnome.org/GNOME/metacity/commit/359f60a6aee5f1338a5edd9f4d84557126c6d46e
=> Fix some deprecation warnings

.build.yml, .travis.yml
Test meson build on Travis CI.
=> [ci] enable meson build on travis

doc/how-to-get-focus-right.txt, src/compositor/compositor-private.h, src/compositor/compositor-xrender.c, src/compositor/compositor.c, src/core/stack.c, src/core/window-private.h, src/core/window.c, src/core/workspace.c, src/core/workspace.h
1 - window: fix crash if workspace is null
2- compositor: fix possible crash closing/destroying window
=> Crash fixes

src/core/keybindings.c
Just a few simple lines of code to be able to move and resize windows using VIM keys.
=> Added VI keys (hjkl) for moving and resizing windows

src/core/window-private.h, src/core/window.c, src/include/window.h
based on https://github.com/GNOME/metacity/commit/2c48b4412f8811e541412017894de6b945e21037
=> window: turn into a GObject

src/compositor/compositor-xrender.c
Make sure tooltips are visible when the source widget is close to the edge of the work area. widget is close to the edge of the work area.
See inline comments - as of 3.24 tooltip positioning is handled
differently, and under certain conditions in hidpi, tooltips for the
bottom panel applets can end up off the bottom of the work area.
To reproduce, in hidpi, set the bottom panel to approximately 30px
tall and try to activate a tooltip for an applet on that panel.
- I'm not too familiar with this compositor, it's possible there's a better place for this sort of fix.
- I had assumed that since panels can be added to any monitor that I could get the precise work area for any monitor (not just for the primary) but that doesn't seem to be possible - tooltips will overlap the panel on a second …
=> compositor-xrender.c: keep tooltips visible in hidpi.

src/core/window.c
When handling a ClientMessage event that removes _NET_WM_STATE_MAXIMIZED_HORZ
or _NET_WM_STATE_MAXIMIZED_VERT from _NET_WM_STATE, marco always restores the
window rectangle to the saved rectangle. So if an application window is already
unmaximized and the application sends such a ClientMessage event, marco will
reset the window rectangle regardless. EWMH doesn't specify what must be done
when handling such events. It seems best to avoid restoring window rectangles
like other window managers in this case.
Fix a related bug: https://bugs.winehq.org/show_bug.cgi?id=50381
This revert a change introduced by 6219f8e8bcaeefb9185a3c3f5f20de4e2fa8f18f.
Signed-off-by: Zhiyi Zhang <zzhang@codeweavers.com>
=> window: Only unmaximize when the window is already maximized.

.build.yml, configure.ac, meson.build, src/core/window-props.c
This patch adresses this issue
https://github.com/mate-desktop/marco/issues/301
tested and works well with flapak.
=> replace _NET_WM_PID with XResGetClientPid

src/ui/tabpopup.c
When composited, the tab popup uses an OSD style which typically has a dark background, so we use a light background highlight color. However, when not composited the popup uses a light color and should thus use a dark highlight.  This was done for the workspace popup (#623), but not for the window one, leading to the highlight being hardly visible in several themes.
With a theme using plain white BG (high contrast):
Before | After
---------|---------------------
=> tabpopup: Use more contrasting background when not composited

src/ui/tabpopup.c
Like #772 but on the main repo for CI purposes.
Fixes #771.
CC @jeremyp3
=> tabpopup: Report the window as active to a11y when it's showing

src/tools/marco-window-demo.c, src/ui/frames.c, src/ui/menu.c, src/ui/resizepopup.c
This fixes all remaining GTK deprecation warnings. No functionality changes.
=> Fix GTK deprecations
